# Generated by Django 4.0.2 on 2022-03-15 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='arrival',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='bus',
            name='fare',
            field=models.FloatField(default=0.0),
        ),
    ]
