# Generated by Django 4.0.2 on 2022-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_bus_arrival_bus_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('arrival', models.TimeField()),
                ('amount', models.FloatField()),
                ('book_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
