# Generated by Django 4.0.2 on 2022-04-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_bookbus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookbus',
            old_name='arrival',
            new_name='bus_arrival',
        ),
        migrations.RenameField(
            model_name='bookbus',
            old_name='destination',
            new_name='bus_destination',
        ),
    ]
