# Generated by Django 4.0.2 on 2022-04-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0004_rename_arrival_bookbus_bus_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbus',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
