# Generated by Django 4.0.2 on 2022-04-09 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0006_bookbus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbus',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookbus',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 9)),
        ),
    ]
